export const DEFAULT_BLOCKS: Record<string, Record<string, unknown>> = {
  homepage: {
    seo: {
      title: 'Aimentra — Learn Smarter with AI-Powered Courses',
      description: 'Join learners who master new skills with AI-guided courses, personalized progress tracking, and verified certificates.',
    },
    sections: [
      { id: 'hero', enabled: true },
      { id: 'stats', enabled: true },
      { id: 'categories', enabled: true },
      { id: 'featuredCourses', enabled: true },
      { id: 'pricing', enabled: true },
      { id: 'testimonials', enabled: true },
      { id: 'faq', enabled: true },
      { id: 'cta', enabled: true },
    ],
  },
  hero: {
    headline: 'Transform Your Business with Expert Coaching',
    subheadline: 'Proven programs in marketing, sales, finance, HR, and mindset — built for Indian entrepreneurs.',
    ctaText: 'View Plans',
    ctaHref: '/packages',
    secondaryCtaText: 'View Plans',
    secondaryCtaHref: '/packages',
    badge: 'Transform Your Business Today',
    heroImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1400&q=80',
    accentWordCount: 2,
    showOverlay: true,
    overlayCardTitle: 'Business Mastery Bundle',
    overlayCardDescription: 'Complete framework for scaling your business to 7 figures within 12 months.',
    overlayProgress: 68,
    overlayProgressLabel: '68% Complete',
    overlayRating: '',
    overlayRatingLabel: '',
    overlayAvatarCount: 4,
  },
  stats: {
    items: [
      { label: 'Students', metric: 'totalStudents', suffix: '+' },
      { label: 'Courses', metric: 'publishedCourses', suffix: '+' },
      { label: 'Years Experience', metric: 'yearsExperience', suffix: '+' },
      { label: 'Avg Rating', metric: 'averageRating', suffix: '', decimals: 1 },
    ],
  },
  categories: {
    title: 'Explore by',
    titleAccent: 'Category',
    subtitle: 'Browse courses organized by the topics that matter most to your business growth.',
    ctaText: 'View All Courses',
    ctaHref: '/courses',
    limit: 8,
  },
  featuredCourses: {
    title: 'Trending',
    titleAccent: 'Masterclasses',
    subtitle: 'Explore our most popular courses designed by industry experts to help you accelerate your career and business growth.',
    ctaText: 'View All Courses',
    ctaHref: '/courses',
    limit: 4,
    source: 'featured',
    categoryId: '',
  },
  pricingSection: {
    title: 'Simple, Transparent Pricing',
    subtitle: 'Choose the plan that best fits your goals. Upgrade, downgrade, or cancel anytime.',
    showBillingToggle: true,
    annualLabel: 'Annual',
    lifetimeLabel: 'Lifetime',
    lifetimeBadge: 'Save 40%',
    guaranteeTitle: '30-Day Money-Back Guarantee',
    guaranteeText: 'Not satisfied? Get a full refund, no questions asked.',
  },
  testimonialsSection: {
    title: 'Trusted by',
    titleAccent: 'Industry Leaders',
    subtitle: 'Hear from professionals who have transformed their careers and businesses with our platform.',
    limit: 4,
    featuredOnly: true,
  },
  faq: {
    title: 'Frequently Asked Questions',
    subtitle: "Have questions? We're here to help. If you don't find your answer, reach out to our support team.",
    items: [
      {
        question: 'What courses do I get access to?',
        answer: 'Access depends on your plan. Gold unlocks all current courses; Premium includes future updates.',
      },
      {
        question: 'How long do I keep access?',
        answer: 'Gold is 1 year from purchase. Premium is lifetime.',
      },
    ],
  },
  footer: {
    tagline: 'Transforming businesses and careers with expert coaching.',
    contactEmail: 'support@aimentra.com',
    contactPhone: '+91 00000 00000',
    socialLinks: { youtube: '', instagram: '', linkedin: '' },
    address: 'India',
  },
  about: {
    heroTitle: 'Transforming Businesses, One Founder at a Time',
    heroSubtitle: "Aimentra is India's trusted AI-powered learning platform, helping students and professionals master skills with intelligent, personalized courses.",
    missionTitle: 'Our Mission',
    missionBody: 'We believe every entrepreneur deserves access to world-class business education — without the jargon, without the fluff.',
    missionSecondary: "Since our founding, we've helped tens of thousands of business owners build the skills, systems, and confidence to grow sustainably.",
    whyChooseUs: ['Practical, Hindi-first course content', 'Verified certificates on completion', 'Lifetime access options', 'Active community & live sessions'],
    values: [
      { title: 'Practical Over Theoretical', desc: 'Every course is built from real business experience.' },
      { title: 'Community-Driven Growth', desc: 'Join entrepreneurs learning and growing together.' },
      { title: 'Proven Results', desc: 'Alumni have scaled businesses using our frameworks.' },
      { title: 'Continuous Innovation', desc: 'Curriculum updated to reflect what works today.' },
    ],
    milestones: [
      { year: '2014', label: 'Founded with a single workshop on business fundamentals' },
      { year: '2018', label: 'Crossed 10,000 students across marketing & sales programs' },
      { year: '2021', label: 'Launched the online coaching platform with 40+ courses' },
      { year: '2026', label: '50,000+ entrepreneurs trained across India' },
    ],
    ctaTitle: 'Ready to start your transformation?',
    ctaSubtitle: 'Join 50,000+ learners building better futures with Aimentra.',
    ctaButtonText: 'Explore Courses',
    ctaButtonHref: '/courses',
  },
  contact: {
    title: 'Get in Touch',
    subtitle: 'Have a question about courses, plans, or your account? We\'re here to help.',
    supportHours: 'Mon–Sat, 10 AM – 7 PM IST',
    supportEmail: 'support@aimentra.com',
    supportPhone: '+91 98765 43210',
    officeAddress: 'Indore, Madhya Pradesh, India',
  },
  cta: {
    badge: 'Limited Time Offer',
    headline: 'Ready to Build the Business of Your Dreams?',
    subheadline: 'Join 50,000+ entrepreneurs who have already transformed their business. Start learning today.',
    primaryButtonText: 'Get Started Today',
    primaryButtonHref: '/packages',
    secondaryButtonText: 'Browse Free Content',
    secondaryButtonHref: '/courses',
    footnote: '7-day money-back guarantee • No hidden fees • Cancel anytime',
  },
  terms: {
    title: 'Terms & Conditions',
    lastUpdated: 'August 2026',
    body: '<h2>1. Acceptance of Terms</h2><p>By accessing Aimentra you agree to these Terms & Conditions.</p><h2>2. Account Registration</h2><p>You must provide accurate information when creating an account.</p><h2>3. Plans & Course Access</h2><p>Access is governed by your active subscription plan.</p>',
  },
  privacy: {
    title: 'Privacy Policy',
    lastUpdated: 'August 2026',
    body: '<h2>1. Information We Collect</h2><p>We collect name, email, phone, and payment details when you register or purchase.</p><h2>2. How We Use Your Information</h2><p>We use data to provide and improve our services.</p>',
  },
  refund: {
    title: 'Refund Policy',
    lastUpdated: 'August 2026',
    body: '<h2>7-Day Money-Back Guarantee</h2><p>Request a full refund within 7 days of purchase if you are not satisfied.</p>',
  },
  coursesPage: {
    title: 'All',
    titleAccent: 'Courses',
    subtitle: 'Expert-led business courses. Learn marketing, sales, finance and more.',
  },
  packagesPage: {
    title: 'Choose Your',
    titleAccent: 'Growth Plan',
    subtitle: 'Invest in your business education. Start with Gold for a year of growth, or go Premium for lifetime access.',
    trustBadges: [
      { text: '7-Day Money-Back' },
      { metric: 'totalStudents', suffix: '+ Students' },
      { metric: 'averageRating', suffix: ' Avg Rating', decimals: 1 },
    ],
    faqTitle: 'Questions?',
    faqTitleAccent: "We've Got Answers",
    faqItems: [
      { question: "What's included in the Gold plan?", answer: "Gold gives you full access to all our courses for the plan's access period. Includes certificates, PDF downloads, and community access." },
      { question: 'What makes Premium worth it?', answer: 'Premium includes lifetime access — you never pay again. You also get all future courses we add, VIP community, priority support, and downloadable content.' },
      { question: 'Is there a money-back guarantee?', answer: 'Absolutely. We offer a full 7-day money-back guarantee. No questions asked.' },
      { question: 'Can I upgrade my plan later?', answer: "Yes! Contact support and we'll arrange a seamless upgrade at a prorated rate." },
      { question: 'Are the courses in Hindi?', answer: 'Yes, all courses are taught in Hindi with practical, simple language designed for Indian entrepreneurs.' },
    ],
    guaranteeTitle: '7-Day Money-Back Guarantee',
    guaranteeText: 'Try any plan risk-free. If you are not satisfied within 7 days, contact us for a full refund.',
  },
};
